#:kivy 1.11.1

<MyLayout>
    orientation: "vertical"
    amount: input_amount.text
    message: lbl_message
    button: button
    padding: 15
    spacing: 15

    Label:
        id: lbl_message
        font_size: 24

    TextInput:
        id: input_amount
        hint_text: "Type the amount..."

    Button:
        background_color: 0, 0, 1, .5
        id: button
        on_press: 
            input_amount.text = ""
        